### ISSUE TITLE
bug&suggestion

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#101]
在 [https://codeforces.com/problemset/problem/1942/d](https://codeforces.com/problemset/problem/1942/d)（注意大小写）中代码框失效。
---
建议添加（测试并提交）功能（样例通过后直接提交）

**Comment by beijixiaohu** [comment]
感谢建议，不过我没有想好一个好的交互方式，直接增加一个这样的按钮应该是不合适的，添加到设置面板中作为一个自定义选项吗，还是有更好的设计呢
