### ISSUE TITLE
1.15.5 版本删除重装 1.15.2 后无法加载

### ISSUE THREAD

**Issue by rksm2329** [beijixiaohu/OJBetter#104]
如题。  
本人在使用 ATBetter 1.15.5 测试版时出现了下拉框不显示、代码框无法输入代码问题，决定重新安装，到油叉重新装了一遍，回来就不能加载了。  
望修复。

**Comment by beijixiaohu** [comment]
你可以试一试清除设置信息：
步骤：
- 修改tampermonkey为高级模式：
  ![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/a1177767-1002-471f-88d2-f3a750839d46)

- 然后打开脚本的编辑页面：
  ![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/8841f3f6-eda2-43b6-8ba9-4e9e6b1bc89b)
- 将下面框中的数据全部删除，然后输入一对花括号
```
{}
```

- 点击保存，即可清除所有设置信息

对于你所说的如下问题：
> 本人在使用 ATBetter 1.15.5 测试版时出现了下拉框不显示、代码框无法输入代码问题

如果仍然在某处复现，请提供页面链接，以及报错信息

**Comment by rksm2329** [comment]
> 你可以试一试清除设置信息： 步骤：
> 
> * 修改tampermonkey为高级模式：
>   ![image](https://private-user-images.githubusercontent.com/60805870/324176746-a1177767-1002-471f-88d2-f3a750839d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTY5MDcsIm5iZiI6MTcxMzYxNjYwNywicGF0aCI6Ii82MDgwNTg3MC8zMjQxNzY3NDYtYTExNzc3NjctMTAwMi00NzFmLTg4ZDItZjNhNzUwODM5ZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYmI2ZjFhYjRmZjM2MTYwYWIxNjUwMzAyODQwMTE3ODM0MWYxZDRkZDlmYzE3YjNlODFkOTdmOTJjNDgxMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9dtaTi_YS3ZEaVdv_lKjf-AD3O6c8SKStKYZSnl1FSk)
> * 然后打开脚本的编辑页面：
>   ![image](https://private-user-images.githubusercontent.com/60805870/324176830-8841f3f6-eda2-43b6-8ba9-4e9e6b1bc89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTY5MDcsIm5iZiI6MTcxMzYxNjYwNywicGF0aCI6Ii82MDgwNTg3MC8zMjQxNzY4MzAtODg0MWYzZjYtZWRhMi00M2I2LThiYTktNGU5ZTZiMWJjODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzI0M2Q0ZWJiODdkYzg5OTVmOWNmMGI1NTI2N2U5NzljYWE5NDg2NzVhZDBkNjAxYmVlMTYwM2RmMjRlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yED21Cy1J84hZ1hNNq69NXfxwnAIk_q4abAAFAlvYAM)
> * 将下面框中的数据全部删除，然后输入一对花括号
> 
> ```
> {}
> ```
> 
> * 点击保存，即可清除所有设置信息
> 
> 对于你所说的如下问题：
> 
> > 本人在使用 ATBetter 1.15.5 测试版时出现了下拉框不显示、代码框无法输入代码问题
> 
> 如果仍然在某处复现，请提供页面链接，以及报错信息

试过了，不能正常加载，只能加载出暗色模式。

**Comment by rksm2329** [comment]
暗色模式是指深色界面

**Comment by rksm2329** [comment]
其他的诸如 ATBetter 选项什么的都没有加载成功。

**Comment by beijixiaohu** [comment]
看看控制台的报错情况

**Comment by beijixiaohu** [comment]
有深色应该是初始化的时候出问题了，深色在初始化前面

**Comment by rksm2329** [comment]
> 有深色应该是初始化的时候出问题了，深色在初始化前面

有一大堆东西，基本全部模块都没有加载

**Comment by rksm2329** [comment]
准确地说是加载错误

**Comment by beijixiaohu** [comment]
发一下控制台截图

**Comment by rksm2329** [comment]
![](https://img2.imgtp.com/2024/04/20/0DDuqhXS.png)

**Comment by rksm2329** [comment]
> 发一下控制台截图
就各种各样的东西，红黄都有

**Comment by rksm2329** [comment]
> 发一下控制台截图

**Comment by beijixiaohu** [comment]
啊？
你这是网络问题吧

**Comment by rksm2329** [comment]
> 啊？ 你这是网络问题吧

啊？我以前开代理打比赛都没问题啊？

**Comment by beijixiaohu** [comment]
你随便打开一个黄色的里面的那个链接
看看能不能访问

**Comment by beijixiaohu** [comment]
是不是你用的代理现在出问题了

**Comment by rksm2329** [comment]
> 你随便打开一个黄色的里面的那个链接 看看能不能访问

解决了解决了，md果然是shift代理的问题，开 geph 之后 lg 都上不去
