### ISSUE TITLE
关于复制代码

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#105]
从剪切板复制代码会出现莫名奇妙的字符导致复制到编译器里不能编译通过
https://codeforces.com/problemset/submission/280/257429460

可能是空行？

**Comment by wrk-123** [comment]
应该是空行的位置插入了一个字符

**Comment by beijixiaohu** [comment]
好的，我看看为什么

**Comment by beijixiaohu** [comment]
现在问题解决了吗

**Comment by wrk-123** [comment]
解决了
