### ISSUE TITLE
插件文字显示错误

### ISSUE THREAD

**Issue by qjwh** [beijixiaohu/OJBetter#108]
插件中除了汉化内容外所有信息几乎都显示异常。

比如显示了“Atcoder Better - loadSuccess”这样的异常显示，包括设置界面几乎所有文字都不显示。

打开源码在“i18next.t('...')”都提示“i18next未定义”。

**Comment by beijixiaohu** [comment]
> 打开源码在“i18next.t('...')”都提示“i18next未定义”。

这里你是指浏览器控制台吗还是

**Comment by qjwh** [comment]
像这样

![QQ截图20240427214203](https://github.com/beijixiaohu/OJBetter/assets/121411508/c440a691-7ea3-42ae-8b24-4ad1e64dd2c8)

**Comment by beijixiaohu** [comment]
这里的提示没关系，i18next是通过cdn引入的，这里肯定会提示未定义

**Comment by beijixiaohu** [comment]
你打开设置面板，点击“刷新缓存”刷新一下试试

![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/aaf44aa1-7b32-432a-88d6-b607be8d2e61)

**Comment by beijixiaohu** [comment]
如果控制台有报错截图发一下

**Comment by qjwh** [comment]
我去at、cf上都看了，没有任何与脚本有关的报错（at报错了一个cdn.d2...的错误，cf都是youtube的错误）

我尝试刷新缓存（甚至恢复到出厂）仍然没有解决/gg

**Comment by beijixiaohu** [comment]
啊这，是突然这样了吗，还是第一次用

**Comment by qjwh** [comment]
突然这样，在昨天的时候

**Comment by beijixiaohu** [comment]
浏览器版本也提供下

**Comment by qjwh** [comment]
Edge最新版124

**Comment by beijixiaohu** [comment]
那你去代码里给i18n的debug打开

**Comment by beijixiaohu** [comment]
我去找找在哪一行，我是手机现在，看代码不方便

**Comment by beijixiaohu** [comment]
![Screenshot_20240427_223202](https://github.com/beijixiaohu/OJBetter/assets/60805870/7998aa0f-9de9-4785-a843-e604383c393b)

改成true

**Comment by beijixiaohu** [comment]
然后控制台就会有详细的日志，你看看是啥问题

**Comment by qjwh** [comment]
报了一堆错误

![image](https://github.com/beijixiaohu/OJBetter/assets/121411508/766e575b-b629-44a3-abb7-54b29f3851bb)

大概可能是没搞到data，然后就加载文字出错

**Comment by beijixiaohu** [comment]
不应该呀，你浏览器打开一个试试

https://aowuucdn.oss-accelerate.aliyuncs.com/resources/locales/codeforces-better/settings.json

看能不能访问

**Comment by qjwh** [comment]
可以访问

**Comment by beijixiaohu** [comment]
那这样吧，你先打开浏览器的控制台，打开网络标签，筛选器中输入`json`

然后打开脚本的设置 - 维护，点击刷新脚本本地化的缓存，然后看看这些请求是否都请求成功了

![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/3a3d112b-a0ef-410d-895f-0a06d5035a5e)

**Comment by qjwh** [comment]
![image](https://github.com/beijixiaohu/OJBetter/assets/121411508/e55c8f33-2856-4042-b3f3-6e0839c98aca)

只有一堆的codeforces-better.json，大概是汉化配置/gg

**Comment by beijixiaohu** [comment]
啊？不可能啊，咋加载了这么多遍codeforces-better.json

**Comment by beijixiaohu** [comment]
脚本本地化的json是不是一个也没有，就我那张图上的

**Comment by beijixiaohu** [comment]
你是不是在哪修改了代码，导致的

这儿是根据这里的代码来加载的

![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/1a33ccd2-e08b-4fb7-8157-b292945a1461)

**Comment by qjwh** [comment]
...

发现问题了，油猴脚本的的脚本列表界面里的“恢复到出厂”如恢复。

现在好了

（我当时在把脚本汉化改成我的json的时候把这里也改了/gg）

**Comment by qjwh** [comment]
当时应该是在改了之后本地化先用了缓存，然后在修改后一周因为强制刷新把错误的json下载了

**Comment by beijixiaohu** [comment]
哈哈好的，刚去看了下你改的，挺好的，可以合到这边来，我这大部分都是copilot生成的，有的翻译的有问题

**Comment by beijixiaohu** [comment]
太多了也懒得去校
