### ISSUE TITLE
翻译崩溃

### ISSUE THREAD

**Issue by shicxin** [beijixiaohu/OJBetter#11]
23/12/15，在使用分段翻译时发现翻译崩溃，切换为普通模式后仍有问题
![image](https://github.com/beijixiaohu/OJBetter/assets/83284782/1c5c4c14-2d00-4e13-95d3-ae9604356add)
重新安装后问题解决

**Comment by shicxin** [comment]
当前网络环境可以正常使用外网

**Comment by beijixiaohu** [comment]
是之前一直能用，然后突然不能用了吗，还是之前没用过分段，第一次用

**Comment by shicxin** [comment]
> 是之前一直能用，然后突然不能用了吗，还是之前没用过分段，第一次用

最近没有更改插件配置，一直使用的是谷歌翻译+分段翻译；
今天在查看这个题单https://codeforces.com/contest/1910/problem/A后，出现了google翻译报错，并且更改分段翻译为普通翻译无反应，更换翻译API无反应，考虑可能是缓存问题重装插件并清除浏览器数据后，使用DeepL+分段翻译无问题；

**Comment by beijixiaohu** [comment]
确实如此，是Google 翻译的网页结构变了，翻译结果的元素会被解析为第一级，因此用`find('.result-container')`就找不到了。

![Snipaste_2023-12-15_14-06-10](https://github.com/beijixiaohu/OJBetter/assets/60805870/621de34e-d422-45f3-8842-186653f1a695)

现已修复，感谢反馈
