### ISSUE TITLE
AtCoder自动翻译

### ISSUE THREAD

**Issue by A1go-3F** [beijixiaohu/OJBetter#122]
北极小狐, 您好
我以前用CodeForces打比赛时用CodeForces Better的自动翻译非常好, 现在打AtCoder比赛时用AtCoder Better就无法自动翻译了, 需要手动点击翻译按钮
能不能麻烦您加上这个自动翻译功能
万分感谢

**Comment by beijixiaohu** [comment]
好的，测试版加上了
