### ISSUE TITLE
可不可以加一个自定义使用GPT翻译时候的提示词的功能？

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [beijixiaohu/OJBetter#123]
因为我自己搭建的LLM好像会误解你写的的提示词，并试图把被翻译的算法题做出来

**Comment by Dawn-Xu-helloworld** [comment]
对了,最好加个开关，因为我看你现在的prompt是作为用户发言输入的
如果要是可以把初始prompt作为system prompt 传入而非作为用户的第一句话，这样可能效果会更好一些（虽然OpenAI的ChatGPT好像不太会关心system prompt）

**Comment by beijixiaohu** [comment]
你是指再提供一种模式，这种模式下会在messages数组中放俩object，一个是让他充当翻译的系统消息，一个是作为用户消息的翻译文本，是这样吗

**Comment by Dawn-Xu-helloworld** [comment]
> 你是指再提供一种模式，这种模式下会在messages数组中放俩object，一个是让他充当翻译的系统消息，一个是作为用户消息的翻译文本，是这样吗

是这样，就是
```json
[
{"role":"system", "content":"系统提示词"}
{"role":"user","content":"需要翻译的东西"}
]
```
然后就直接做成一个单独的选项，开启的话发送这样的数据
不开启的话把系统提示词和需要翻译的句子用回车符隔开一块发过去就行，系统提示词留空

**Comment by beijixiaohu** [comment]
好的，明个我看有空不，有空加上

**Comment by Dawn-Xu-helloworld** [comment]
我发现了幻觉的真正原因：
问题出在发给LLM的请求上，这个插件实际传入的是
```JSON
{
"model":"MODEL_NAME",
"messages":[
    {"role":"assistant","content":"请求翻译的prompt"}
]
}
```
这个assistant的role是用来让LLM了解在 “这次用户提问之前LLM说过什么”的，也就是LLM的上下文记忆能力的来源，而用户询问LLM的内容应该把请求里的`role`设为`user`。

**Comment by beijixiaohu** [comment]
> 我发现了幻觉的真正原因：
> 问题出在发给LLM的请求上，这个插件实际传入的是
> ```JSON
> {
> "model":"MODEL_NAME",
> "messages":[
>     {"role":"assistant","content":"请求翻译的prompt"}
> ]
> }
> ```
> 这个assistant的role是用来让LLM了解在 “这次用户提问之前LLM说过什么”的，也就是LLM的上下文记忆能力的来源，而用户询问LLM的内容应该把请求里的`role`设为`user`。

原来如此，感谢分享，下午我给改下

**Comment by Dawn-Xu-helloworld** [comment]
要不我PR一个

**Comment by beijixiaohu** [comment]
好
