### ISSUE TITLE
[功能请求] 可以为 monaco 添加无缓存的设置选项吗？

### ISSUE THREAD

**Issue by funcdfs** [beijixiaohu/OJBetter#124]
![image](https://github.com/beijixiaohu/OJBetter/assets/56250171/862fc37a-526f-4c4d-80ae-020e9d384ef8)

场景描述：

- 第一次提交 wa 掉
- 然后第二次打开页面粘贴的时候发现之前的代码还在
- 需要手动 删除，然后再复制
- 如果默认空白就方便很多（如同 Vjudge 默认的提交表格一样）

因为如果是用 vscode 之类的编辑器写代码，monaco 作为提交工具的话，这里的缓存在每次提交的时候就要手动 Ctrl+A，删除，Ctrl+V 。

如果设置成， **提交代码/刷新页面 之后，浏览器页面的 monaco 编辑器自动还原为默认的空白 monaco**，  
这样就不用每次全选然后删除了，在交代码的时候只需要粘贴一次，不用额外的做重复动作（在浏览器中再进行修改）。
并且避免了忘记修改导致的提交相同代码的问题。

当然，这只是我个人觉得可以改进的功能，缓存功能应该也是您专门写的，还望大佬考虑实现一个开关选项（如同其他选项一样）。

**Comment by beijixiaohu** [comment]
好的
