### ISSUE TITLE
之前一个pr的一个小误

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#128]
8622行

`translateDiv.updateTranslateDiv(translatedText, !((OJBetter.typeOfPage.is_oldLatex || OJBetter.typeOfPage.is_acmsguru) && (OJBetter.translation.forceTurndownConversion)));`

应该为

`translateDiv.updateTranslateDiv(translatedText, !((OJBetter.typeOfPage.is_oldLatex || OJBetter.typeOfPage.is_acmsguru) && (!OJBetter.translation.forceTurndownConversion)));`

（加一个`!`，不想为了这个再pr一次。）

**Comment by beijixiaohu** [comment]
好的，明天我改下
