### ISSUE TITLE
AtCoder 中的一些比赛无法跳转至洛谷，显示未找到

### ISSUE THREAD

**Issue by beijixiaohu** [beijixiaohu/OJBetter#130]
rt

e.g.

https://atcoder.jp/contests/dwacon6th-prelims/tasks/dwacon6th_prelims_c/

↓

https://www.luogu.com.cn/problem/AT_dwacon6th_prelims_c

**Comment by Physics212303** [comment]
这个东西在正则表达式匹配里面特判一下下划线就可以了。
