### ISSUE TITLE
将 Codeforces 重现赛提交页的状态显示模拟为ICPC风格

### ISSUE THREAD

**Issue by beijixiaohu** [beijixiaohu/OJBetter#139]
增加一个可选的小功能：在gym里vp一场比赛时，MY SUBMISSIONS页面的每个SUBMISSION不显示未通过时测试点的编号，而是单独显示提交状态（例如AC、WA、TLE），更加模拟ICPC赛制比赛的规则

建议：[ZhgDgE](https://greasyfork.org/zh-CN/users/1312793-zhgdge)

**Comment by wrk-123** [comment]
事实上，可不可以考虑用一些自定义的一些格式来显示反馈信息：
比如默认的 {NAME} (on test {testid})
按照此处的描述，直接是 {NAME}
此处的规则是 {NAME} 表示反馈名称（Accepted，Wrong Answer，...）。{testid} 表示最后一个所测测试点编号（AC时候为 0），”()“内内容在AC时不显示。
可以加一个 {name} ,表示反馈简称（AC，WA，...）等。
（不过这个规则可能有点复杂）

**Comment by beijixiaohu** [comment]
> 事实上，可不可以考虑用一些自定义的一些格式来显示反馈信息： 比如默认的 {NAME} (on test {testid}) 按照此处的描述，直接是 {NAME} 此处的规则是 {NAME} 表示反馈名称（Accepted，Wrong Answer，...）。{testid} 表示最后一个所测测试点编号（AC时候为 0），”()“内内容在AC时不显示。 可以加一个 {name} ,表示反馈简称（AC，WA，...）等。 （不过这个规则可能有点复杂）

好主意！

**Comment by wrk-123** [comment]
您已发送成功，邮件已经被发送到收件人的邮箱当中。这是一封自动回复的邮件，收件人可能并没有立即收到消息。
