### ISSUE TITLE
似乎有个问题

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#146]
![1232](https://github.com/beijixiaohu/OJBetter/assets/83344959/c0d942ab-c909-40d8-97dd-02eb5932bff3)
这咋没有提示信息呢？

**Comment by wrk-123** [comment]
原来很长的标题是复制错了。

**Comment by beijixiaohu** [comment]
有吧，我这有，你刷新下缓存试试
![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/5e16af01-ca57-4c00-94d0-1b6c497aa270)
