### ISSUE TITLE
使用自定义接口的ChatGPT翻译时会被浏览器拦截

### ISSUE THREAD

**Issue by mywwzh** [beijixiaohu/OJBetter#149]
浏览器版本：Microsoft Edge 版本 126.0.2592.61。

AtCoder Better 和 Codeforces Better均存在此问题，在添加自定义接口的ChatGPT翻译后，点击翻译按钮就会被浏览器强行拦截，错误代码: `STATUS_ACCESS_VIOLATION`。

![image](https://github.com/beijixiaohu/OJBetter/assets/126879177/678d2c79-d8c3-4c44-8fca-dbc9a1ef4cb3)

![image](https://github.com/beijixiaohu/OJBetter/assets/126879177/34c34ed1-3bd9-4807-a8aa-462b9125df8f)

**Comment by beijixiaohu** [comment]
无法复现，请提供控制台的报错信息

**Comment by cby998877** [comment]
> 无法复现，请提供控制台的报错信息

有时候行,有时候不行啊?我2分钟前还行刷新一下又 不行了
