### ISSUE TITLE
添加自定义的翻译接口

### ISSUE THREAD

**Issue by ac-yingyaoyao** [beijixiaohu/OJBetter#150]
问题：有些翻译 并不是很准确 ，但是自己又没有购买gpt api。但是自己在 本地 / 远程 搭建了一个翻译服务(比如是一个http get请求 或者 sse 的流式返回)

期待：能支持一个自定义的翻译接口，能支持 http get / post 或者 sse

**Comment by beijixiaohu** [comment]
这可能比较复杂，暂不计划实现，不过你可以自行修改你的翻译服务的返回信息，或者添加一个中间层，使返回结果的格式符合openai的格式，这样你就可以直接将其填写在chatgpt的配置中了
