### ISSUE TITLE
更换库 CDN

### ISSUE THREAD

**Issue by beijixiaohu** [beijixiaohu/OJBetter#151]
由于最近 cdn.staticfile.net 在一些地区出现了无法访问或者疑似被劫持的问题，故准备更换为 cdn.bytedance.com

**Comment by beijixiaohu** [comment]
cdn.bytedance.com 似乎长期未维护，放弃更换，

脚本最开始使用的是 www.bootcdn.cn，遇到过好几次故障，然后换到了现在的 cdn.staticfile.net，但是现在也不太稳定了

如有好的公共库 CDN 服务，欢迎推荐

**Comment by famousprince** [comment]
https://greasyfork.org/en/discussions/development/249443-polyfill-supply-chain-attack-bootcdn-and-staticfile

bootcdn & staticfile 已坐实投毒，已被 greasyfork 拉黑

可以考虑 mirrors.sustech.edu.cn/cdnjs/ajax/libs，如果有些库没有更新也可以尝试 s4.zstatic.net/ajax/libs

**Comment by beijixiaohu** [comment]
> https://greasyfork.org/en/discussions/development/249443-polyfill-supply-chain-attack-bootcdn-and-staticfile
> 
> bootcdn & staticfile 坐实投毒，已被 greasyfork 拉黑
> 
> 可以考虑 mirrors.sustech.edu.cn/cdnjs/ajax/libs，如果有些库没有更新也可以尝试 s4.zstatic.net/ajax/libs

感谢提醒和建议，不过这两个镜像目前不在 greasyfork 的允许名单中，无法使用

https://greasyfork.org/zh-CN/help/cdns

**Comment by czr2012** [comment]
~~后排围观各位大佬讨论~~

**Comment by Francklin** [comment]
可以试试webcache.cn，支持cdnjs, npm和github，支持SRI

**Comment by beijixiaohu** [comment]
> 可以试试webcache.cn，支持cdnjs, npm和github，支持SRI

哈哈感谢自荐，以后有需要时会考虑的。
