### ISSUE TITLE
题目页的代码编辑器偶尔出现无法使用

### ISSUE THREAD

**Issue by 2410017640** [beijixiaohu/OJBetter#153]
![QQ_1720065394940](https://github.com/beijixiaohu/OJBetter/assets/141049810/afd694bb-0dfb-46a8-9f14-52df0724824c)

**Comment by 2410017640** [comment]
触发原因未知

**Comment by 2410017640** [comment]
切换语言，和刷新重启都没有效果

**Comment by beijixiaohu** [comment]
是测试版还是正式版

**Comment by HengeZi** [comment]
升级到测试版后就能用了

**Comment by beijixiaohu** [comment]
> 正式版

切换到测试版试试

**Comment by beijixiaohu** [comment]
> 升级到测试版后就能用了

原因见 #151 因为目前测试版更新了，稍后更新正式版的
