### ISSUE TITLE
代码编辑器的“更多设置”图标显示不正确

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#158]
![Screenshot 2024-07-06 183823](https://github.com/beijixiaohu/OJBetter/assets/83344959/fb97003f-fa53-4f33-9cc9-a45fd36b7013)
目前脚本语言是中文，已经清空缓存测试。

**Comment by beijixiaohu** [comment]
应该是浏览器缓存，你打开开发者工具-网络，临时给停用缓存勾上，刷新试试
![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/b1fcfdc9-f2a6-499d-8ffe-5c309e4124d3)

**Comment by wrk-123** [comment]
图标出来了，但是文字还是moresetting

**Comment by beijixiaohu** [comment]
发现了，忘了改了之前，现在应该好了
