### ISSUE TITLE
设置黑暗模式为"跟随系统"时，代码块美化未正确切换主题

### ISSUE THREAD

**Issue by YuiHrsw** [beijixiaohu/OJBetter#164]
Monaco 编辑器似乎自带深色和浅色主题, 可以在插件设置页面添加一个选项支持深色/浅色主题切换.

**Comment by beijixiaohu** [comment]
插件的黑暗模式下用的就是monaco自带的深色主题呀

**Comment by YuiHrsw** [comment]
切换到黑暗模式解决了.但是当选择主题模式为跟随系统且勾选美化代码块时,深色模式下仍然是浅色主题.
![屏幕截图 2024-07-17 201706](https://github.com/user-attachments/assets/04f7a43e-80f2-48cd-91cf-d1082c64f5ee)
