### ISSUE TITLE
atcoder翻译完成后代码框不可滚动

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#167]
https://atcoder.jp/contests/abc365/editorial/10584

**Comment by beijixiaohu** [comment]
确实，有空我看看为啥，右侧的滚动条还是能拖动的，好像是monaco的聚焦卡在那儿了

**Comment by wrk-123** [comment]
> 确实，有空我看看为啥，右侧的滚动条还是能拖动的，好像是monaco的聚焦卡在那儿了

bug2：使用deepl翻译该页面翻译内容为空：https://atcoder.jp/contests/arc181/editorial/10615

**Comment by beijixiaohu** [comment]
> > 确实，有空我看看为啥，右侧的滚动条还是能拖动的，好像是monaco的聚焦卡在那儿了
> 
> bug2：使用deepl翻译该页面翻译内容为空：https://atcoder.jp/contests/arc181/editorial/10615

我这儿好像是正常的
![image](https://github.com/user-attachments/assets/d1e52146-ece2-445d-ba95-4d3d2d5d4de3)

**Comment by beijixiaohu** [comment]
> > 翻译内容为空基本不可能是脚本本身的bug，一般都是翻译服务出问题了
> 
> 好像现在好了。建议给出“空”的提示

好的，我还没遇到过空的，遇到了再加上，不然我也不知道是哪里导致空的

**Comment by wrk-123** [comment]
> > > 翻译内容为空基本不可能是脚本本身的bug，一般都是翻译服务出问题了
> > 
> > 
> > 好像现在好了。建议给出“空”的提示
> 
> 好的，我还没遇到过空的，遇到了再加上，不然我也不知道是哪里导致空的

现在发现不只是代码滚动了，原有的包括链接、折叠块也打不开。

**Comment by wrk-123** [comment]
https://atcoder.jp/contests/arc182/editorial/10672

**Comment by beijixiaohu** [comment]
> https://atcoder.jp/contests/arc182/editorial/10672

还真是，好像是样式问题，具体原因还没细看，给这个样式去了就好了，我再看看为啥
![image](https://github.com/user-attachments/assets/4386fbc0-119b-49d1-9081-aefa8d6ec9c6)

**Comment by beijixiaohu** [comment]
我知道为啥了，稍后更新
