### ISSUE TITLE
对于有多个版本的评论，查看之前评论会导致翻译按钮消失。

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#177]
https://codeforces.com/blog/entry/133206?#comment-1196787
![from](https://github.com/user-attachments/assets/bfd7296b-587f-4229-9bc2-c4ec13ccc47e)
![to](https://github.com/user-attachments/assets/43663084-d1bb-421b-9883-83078414733a)

**Comment by beijixiaohu** [comment]
新的浏览器扩展中重新设计了实现方式，已经完美解决了这个问题，至于现在的脚本应该不会去修复了。

![2024年9月16日](https://github.com/user-attachments/assets/b63b5647-12ea-4dea-99ed-fbf5377c0fe7)
