### ISSUE TITLE
Codeforces Better!无法正常使用

### ISSUE THREAD

**Issue by jdkrbfk** [beijixiaohu/OJBetter#178]
Codeforces Better!经常出现无法翻译的情况，重新下载安装后出现Codeforces Better!未工作的情况

**Comment by beijixiaohu** [comment]
请提供更详细的描述，比如报错信息、截图、运行环境

**Comment by jdkrbfk** [comment]
![image](https://github.com/user-attachments/assets/3185cdab-b7b5-4301-919f-becd5ac8f623)
![无标题](https://github.com/user-attachments/assets/52d8c798-529f-4d18-977e-a9e8264b6d9d)
经常出现这样的情况

**Comment by beijixiaohu** [comment]
这不字面意思，人家deepl给你封了

**Comment by beijixiaohu** [comment]
wiki里面有解释 https://github.com/beijixiaohu/OJBetter/wiki/%E7%BF%BB%E8%AF%91

**Comment by jdkrbfk** [comment]
谢谢谢谢，我选择换个翻译服务，已解决

**Comment by ggg16999** [comment]
> wiki里面有解释 https://github.com/beijixiaohu/OJBetter/wiki/%E7%BF%BB%E8%AF%91
大佬好，那三个键经常加载不出来是什么情况呢？就mathjax和翻译那三个键。

**Comment by beijixiaohu** [comment]
> 大佬好，那三个键经常加载不出来是什么情况呢？就mathjax和翻译那三个键。

@ggg16999 你好，请开一个新的issue提问，并且具体一点，我不清楚你说的加载不出来是什么意思
