### ISSUE TITLE
能不能搞一个类似于Comfortable Atcoder的功能

### ISSUE THREAD

**Issue by znzryb** [beijixiaohu/OJBetter#182]
<img width="573" alt="image" src="https://github.com/user-attachments/assets/a02fab6f-b2c0-4ed2-885e-56cf6cd54de1">
如图所示，点击问题可以形成一个问题清单，迅速切换到别的题目，不用再到tasks界面再切换题目

**Comment by beijixiaohu** [comment]
可以，有空我给加上去

**Comment by znzryb** [comment]
> 可以，有空我给加上去

好的，谢谢啦
