### ISSUE TITLE
codeforces better插件失效

### ISSUE THREAD

**Issue by ShimuGuyue** [beijixiaohu/OJBetter#186]
这款插件我用了半年多一直好好的，但最近几天突然不生效了，试过重启浏览器、重启电脑、卸载插件重新安装等方式均没有生效

**Comment by beijixiaohu** [comment]
插件本身肯定是正常的，应该是你那边的问题，你截几张图看看

**Comment by ShimuGuyue** [comment]
这里可以看到插件是打开的，但cf页面却没有显示（我同学的能正常用）
删除重装过程详见附件中的视频录制




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题：回复： [beijixiaohu/OJBetter] codeforces better插件失效 （Issue #186）





 
插件本身肯定是正常的，应该是你那边的问题，你截几张图看看
 
—
直接回复此电子邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该线程。Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

屏幕录制 2024-11-15 123344.mp4 (1K, 2024年12月15日 12:33 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=67656234cdc0b8c463bd62b41464061f4c11570653020c521954570c5149025557064f070552571d025651055057020250045404327a34f6f5a1d9f68eb2f210065550001f55051d0550420500570704004b0f44066409&code=4eb42d40

**Comment by beijixiaohu** [comment]
![image](https://github.com/user-attachments/assets/ae25975d-4706-4c74-a1cf-846801a58726)

这是新版本chrome的安全策略改变导致的，现在需要开启扩展管理页面的那个开发者选项才能使用脚本管理器

![image](https://github.com/user-attachments/assets/325f34f5-3529-403d-88a0-2339c1b204f8)

**Comment by ytlzzz-y** [comment]
我也出现了一样的问题，通过卸载重装篡改猴解决了

**Comment by ShimuGuyue** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的来信我以收到，我将在阅读邮件后尽快给您回复。
