### ISSUE TITLE
希望可以添加自动在文本过长时切换到分段翻译模式

### ISSUE THREAD

**Issue by JYRowe** [beijixiaohu/OJBetter#196]
如题，每次弹出超出字符上限的框时都需要切成分段看完博客再切换回去。

**Comment by JYRowe** [comment]
好像已经有类似的建议  #171  了，但是偶尔题目也会过长。

**Comment by beijixiaohu** [comment]
这个是因为当初代码结构设计的不好，导致是没法实现自动切换分段不分段的，切换了就得重新刷新，不然会有问题，

不过新的扩展 #172  是支持的，理论上一次能翻译无限长的文本，会自动进行分割。旧的就不改了，工作量挺大而且没啥意义。
