### ISSUE TITLE
CF 翻译的文本替换把提交记录页面的题目名称中的关键词也替换了

### ISSUE THREAD

**Issue by JYRowe** [beijixiaohu/OJBetter#198]
（提交记录页面）

![image](https://github.com/user-attachments/assets/c90269e3-06e4-4a52-9cd5-80a2162fd093)

（原题）

![image](https://github.com/user-attachments/assets/a10e2eda-f59b-47d1-88e4-be26d5fc120c)

还见过把 `language` 翻译成了 `语言uage` 的……

**Comment by beijixiaohu** [comment]
该问题之前已经讨论过，见 #120
