### ISSUE TITLE
UI优化建议

### ISSUE THREAD

**Issue by lishufood** [beijixiaohu/OJBetter#39]
1.提交按钮位置
看题页面的提交模块，我很喜欢，很方便
就我和附近同学的习惯都是在idea中调试好代码+样例测试后，复制代码后提交。
页面中的提交按钮在代码块的下方，需要滚轮滑一下才可以找到，体验不够顺滑。
考虑一些用户可能会用这个代码块来检查一下代码，我希望在代码块顶部（“全屏 固定到底部 固定到右侧”附近）新增一个提交按钮

2.返回按钮位置不统一
“固定到底部 固定到右侧”中的“取消固定”按钮在右下角
“全屏”中的“退出全屏”按钮在右上角
希望可以统一成右下角。
（要是三个按钮都叫做“退出”的话，我个人会更喜欢）

3.返回按钮位置
右下角的按钮位置和边框有些冲突，不大好看，建议适当调高
![image](https://github.com/beijixiaohu/OJBetter/assets/53896205/e79f5dc8-4abd-4556-8bb6-3f49aa18e86a)

一些扣细节的想法，见谅

**Comment by beijixiaohu** [comment]
感谢你的建议，会进行调整
