### ISSUE TITLE
1

### ISSUE THREAD

**Issue by shfoda** [beijixiaohu/OJBetter#44]
为什么我用脚本编译器提交后他会跳转到cf的提交页面，点提交始终没用

**Comment by shfoda** [comment]
就某一个题目，第一次交的时候是正常的，后来不知道为什么就成了上面这样

**Comment by beijixiaohu** [comment]
比赛时还是平时练习呢，题目的链接发下

**Comment by shfoda** [comment]
e,为什么我把编译器的代码一换，然后就又能用了。。。。。。。

**Comment by beijixiaohu** [comment]
啊好吧，可能是出了啥小bug，我没遇到过
