### ISSUE TITLE
[Feature] Codeforces Better 和 cf-fast-submit 插件不兼容

### ISSUE THREAD

**Issue by Ethan-ZYF** [beijixiaohu/OJBetter#6]
- cf-fast-submit 插件支持在题目页面下面提交代码，不需要打开submit界面，选题目，提交。
    - 仓库链接: https://github.com/LumaKernel/cf-fast-submit
    - 效果:
      <img width="725" alt="image" src="https://github.com/beijixiaohu/OJBetter/assets/90292101/fd82bded-8568-4420-9430-b236f66273d2">

- 打开codeforces better会导致cf-fast-submit失效，可以考虑兼容一下或者添加一下类似功能。

**Comment by beijixiaohu** [comment]
感谢反馈，这是因为该脚本是通过查找是否存在Logout字符来判断是否已登录

```js
const logged = !!$('a').filter((_, el) => $(el).text() === 'Logout').length
```
当开启 codeforces better 的汉化功能后，
Logout字符被替换为了“退出登录”，因此脚本认为没有登录。

因此你应该修改该脚本的第33行为：

```js
const logged = !!$('a').filter((_, el) => {
  const text = $(el).text();
  return text === 'Logout' || text === '退出登录';
}).length;
```

暂不考虑向 codeforces better 中添加类似功能

**Comment by Ethan-ZYF** [comment]
明白了，谢谢指导
