### ISSUE TITLE
翻译的时候老是弹出，请问可以关掉么

### ISSUE THREAD

**Issue by Fantasy404** [beijixiaohu/OJBetter#61]
弹窗内容如下

"是否继续翻译？
即将翻译的内容似乎为代码片段，翻译它可能是无意义的，你确定继续吗？"

请问可以默认自动翻译别一直弹出来么，翻译一段弹一段

**Comment by beijixiaohu** [comment]
感谢反馈，当时想的就是自动翻译的时候不弹出，可能后面写漏了，这两天身边没电脑看不了，到时候给修复下

**Comment by beijixiaohu** [comment]
欸我试了下，没有复现，自动翻译时会跳过代码片段，可以提供一个可以复现的链接吗

相关代码没看出明显的问题

![Snipaste_2024-02-24_14-26-32](https://github.com/beijixiaohu/OJBetter/assets/60805870/d37bde5e-03ce-4a34-9a43-2b35324898a6)
