### ISSUE TITLE
翻译某些题目时错误地判断为代码片段

### ISSUE THREAD

**Issue by zhicheng-hzc** [beijixiaohu/OJBetter#62]
![图片1](https://github.com/beijixiaohu/OJBetter/assets/138845897/3ea7fd07-b916-4625-806c-0ee2464350cd)

如图。翻译某些题目时错误地判断为代码片段。似乎只存在于某些远古题目中。点“是”后可以成功翻译。（图中题目为 CF656G）

**Comment by beijixiaohu** [comment]
收到，感谢反馈
