### ISSUE TITLE
[BUG]: Atcoder Editorial 的代码块没有应用黑色模式

### ISSUE THREAD

**Issue by GrainRainy** [beijixiaohu/OJBetter#7]
![image](https://github.com/beijixiaohu/OJBetter/assets/77619434/7e6c93d4-f318-45b7-bfca-a1978fe83189)

**Comment by beijixiaohu** [comment]
感谢反馈，进行了简单的反色处理，语法高亮颜色可能不太合适。

官方使用的是 prettify 库高亮代码，样式定义在 [prettify.css](https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/prettify.css)，如果你有兴趣，欢迎手动调整并分享
