### ISSUE TITLE
部分页面代码被吞。（测试版）

### ISSUE THREAD

**Issue by wrk-123** [beijixiaohu/OJBetter#81]
https://codeforces.com/contest/1943/submission/251772063
看不见代码
![nocode](https://github.com/beijixiaohu/OJBetter/assets/83344959/c16fb84d-2307-4dcb-93fa-4c3f1b537dba)

**Comment by beijixiaohu** [comment]
我这能看到
![image](https://github.com/beijixiaohu/OJBetter/assets/60805870/71b1ab9b-14f2-4f46-9850-5e98da232dca)
你刷新试试

**Comment by beijixiaohu** [comment]
如果不行，请提供下浏览器版本信息和控制台有无报错

**Comment by wrk-123** [comment]
从https://codeforces.com/submissions/WRKRW进入不可以看到，
![aaac](https://github.com/beijixiaohu/OJBetter/assets/83344959/66adc5ac-9ae9-4445-9ada-3581f6f913f4)

**Comment by beijixiaohu** [comment]
没有复现，不过看报错应该是monaco库还没有加载好就执行了这里，后面我改进下，感谢反馈

而且我发现这里语法高亮是有问题的，highlight库给这代码判断成kotlin了。。

**Comment by beijixiaohu** [comment]
新版本解决问题了吗

**Comment by wrk-123** [comment]
> 新版本解决问题了吗

解决了，谢谢

**Comment by wrk-123** [comment]
解决了，谢谢
