### ISSUE TITLE
The new 1.74.0 had issues in viewing code in dark mode

### ISSUE THREAD

**Issue by silentwings2004** [beijixiaohu/OJBetter#89]
The code is shown as below in dark mode:

<img width="504" alt="image" src="https://github.com/beijixiaohu/OJBetter/assets/12128822/ffc7d662-ea1a-47ad-9f7e-c8b99ab83ecb">

**Comment by beijixiaohu** [comment]
Thanks for your feedback! Can you drop a link? I haven't come across the issue you mentioned.

**Comment by beijixiaohu** [comment]
fixed
