### ISSUE TITLE
关于 Codeforces Better 翻译功能的小 bug

### ISSUE THREAD

**Issue by CreMicro** [beijixiaohu/OJBetter#9]
部分加粗文字会翻译成 “****” ，bug 稳定复现于 [https://codeforces.com/contest/1766/problem/E](url) 中的第二行的“**个子序列”

**Comment by beijixiaohu** [comment]
这个问题已经收到过反馈了，这是deepl的问题，它吞掉了这个**里面的内容，下次更新会添加一个选项：过滤文本中的 ** 符号

当然你也可以使用别的翻译服务，ChatGPT不会有这个问题

另由于最近没有空闲时间，加上脚本新增的未发布的功能存在一定问题，下一次更新得下下周以后了
